apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: iamrole.easyaas.dev
spec:
  scope: Namespaced
  group: easyaas.dev
  names:
    kind: IamRole
    plural: iamroles
    singular: iamrole
    shortNames:
      - iam
    categories:
      - easyaas

  versions:
    - name: v1
      served: true
      storage: true

      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                policy:
                  type: string
            status:
              type: object
              properties:
                conditions:
                  type: array
                  items:
                    type: object
                  x-kubernetes-preserve-unknown-fields: true
                ready:
                  type: boolean
                kopf:
                  type: object
              x-kubernetes-preserve-unknown-fields: true
      subresources:
        status: {}
