apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: ephemeralnamespaces.easyaas.dev
spec:
  scope: Namespaced
  group: easyaas.dev
  names:
    categories:
      - easyaas
    kind: EphemeralNamespace
    plural: ephemeralnamespaces
    singular: ephemeralnamespace
    shortNames:
      - ens

  versions:
    - name: v1
      served: true
      storage: true

      additionalPrinterColumns:
        - name: Expires
          type: string
          description: Date and Time at which the namespace will be deleted
          jsonPath: .spec.expiresAt
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                expiresAt:
                  type: string
            status:
              type: object
              properties:
                conditions:
                  type: array
                  items:
                    type: object
                  x-kubernetes-preserve-unknown-fields: true
                ready:
                  type: boolean
                kopf:
                  type: object
              x-kubernetes-preserve-unknown-fields: true
      subresources:
        status: {}
