apiVersion: core.easyaas.dev/v1
kind: TerraformResource
metadata:
  name: ephemeralnamespaces
  namespace: easyaas
spec:
  crd: ephemeralnamespaces.easyaas.dev
  terraform:
    source: github.com/nilscan/easyaas-resources//ephemeral-namespaces/terraform
  controllers:
    - name: ephemeralnamespaces-controller
      source: controller/ephemeral-namespaces-controller.py
  extraRoles:
    - name: ephemeralnamespaces-job
      kind: ClusterRole
