apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: ssmparameter.easyaas.dev
spec:
  scope: Namespaced
  group: easyaas.dev
  names:
    kind: SSMParameter
    plural: ssmparameters
    singular: ssmparameter

  versions:
    - name: v1
      served: true
      storage: true

      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                name:
                  type: string
                value:
                  type: string
                type:
                  type: string
            status:
              type: object
              properties:
                conditions:
                  type: array
                  items:
                    type: object
                  x-kubernetes-preserve-unknown-fields: true
                ready:
                  type: boolean
                kopf:
                  type: object
              x-kubernetes-preserve-unknown-fields: true
      subresources:
        status: {}
